apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.api_gateway.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api-gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "api-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          {{- range $k, $v := .Values.api_gateway }}
          - name: {{ $k }}
            value: '{{ $v }}'
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{ if eq .Values.image.tag "" }}
          image: "{{ .Values.api_gateway.image.repository }}"
          {{ else }}
          image: "{{ .Values.api_gateway.image.repository }}:{{ .Values.common.image.tag | default .Chart.AppVersion }}"
          {{ end }}
          imagePullPolicy: {{ .Values.api_gateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8095
              protocol: TCP
          args:
            - /bin/sh
            - -c
            - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 8095
            initialDelaySeconds: 60
            timeoutSeconds: 30     
          resources:
            {{- toYaml .Values.api_gateway.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.rbacVolume.name }}
              mountPath: {{ .Values.rbacVolume.path }}
              readOnly: true
      volumes:
        - name: {{ .Values.rbacVolume.name }}
          configMap:
            name: {{ .Values.rbacConfig.name }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
