---

- name: setup group
  group: name={{ zookeeper_user }} system=yes

- name: Setup user
  user: name={{ zookeeper_user }} system=yes group={{ zookeeper_user }}

- import_tasks: Debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'
