---
- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Add Elastic GPG key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Add Elastic repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present
    filename: "elastic-8.x.list"

- name: Install specific version
  apt:
    name: "elasticsearch=8.17.4"
    state: present
    update_cache: yes

- name: Start and enable service
  service:
    name: elasticsearch
    state: started
    enabled: yes
