apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Release.Namespace }}
data:
  location.list: |-
{{ if .Values.location_list }}
{{ .Values.location_list | indent 4 }}
{{ else }}
    location /healthz {
      return 200 'OK';
    }
    location /.well-known {
      proxy_set_header Host $http_host;
      set $target http://certbot.{{.Release.Namespace}}.svc.cluster.local; 
      proxy_pass $target;
    }    
    location /grafana {
      proxy_set_header Host $http_host;
      rewrite /grafana/(.*) /$1 break;
      set $target http://monitoring-grafana.monitoring.svc.cluster.local;
      proxy_pass $target;
    }
    location /api/ {
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      rewrite /api/(.*) /$1 break;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Host $host;
      client_max_body_size 500M;
      set $target http://api-gateway.{{.Release.Namespace}}.svc.cluster.local:8095;
      proxy_pass $target;
    }
    location /auth {
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Host $host;
      set $target http://keycloak.keycloak.svc.cluster.local:8080;
      proxy_pass $target;
    }
    location / {
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      set $target http://superset.{{.Release.Namespace}}.svc.cluster.local:8088;
      proxy_pass $target;
    }
    location /api/v1/ {
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      set $target http://superset.{{.Release.Namespace}}.svc.cluster.local:8088;
      proxy_pass $target;
    }
{{ end }}
  sites.conf: |-
{{ if .Values.sites_conf }}
{{ if .Values.hcx_ssl.enabled }}
{{ .Values.sites_conf | indent 4 }}
{{ else }}
    # Ref: https://github.com/openresty/openresty/#resolvconf-parsing
    resolver local=on;
    # Need real ip address for flags in replay.
    # Some LBs will forward real ips as x-forwarded-for
    # So making that as priority
    map $http_x_forwarded_for $real_ip {
        ~^(\d+\.\d+\.\d+\.\d+) $1;
        default $remote_addr;
    }
    map $http_upgrade $connection_upgrade {
      default upgrade;
      '' close;
    }
    server {
      listen 80 default_server;
      listen [::]:80 default_server;
      # server_name _;
      include /etc/nginx/conf.d/location.list;
    }
{{ end }}
{{ end }}
