apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hcx-registry.fullname" . }}
  labels:
    {{- include "hcx-registry.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.hcx_registry.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hcx-registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hcx-registry.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hcx-registry.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          {{- range $k, $v := .Values.hcx_registry }}
          - name: {{ $k }}
            value: '{{ $v }}'
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{ if eq .Values.image.tag "" }}
          image: "{{ .Values.hcx_registry.image.repository }}"
          {{ else }}
          image: "{{ .Values.hcx_registry.image.repository }}:{{ .Values.common.image.tag | default .Chart.AppVersion }}"
          {{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          args:
            - /bin/sh
            - -c
            - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 60
            timeoutSeconds: 30   
          resources:
            {{- toYaml .Values.hcx_registry.resources | nindent 12 }}
          volumeMounts:
          - name: registryschemas
            mountPath: /home/opensaber/config/public/_schemas
      volumes:
      - name: registryschemas
        configMap:
          name: registryschemas
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
