apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hcx-provider-service.fullname" . }}
  labels:
    {{- include "hcx-provider-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.hcx_provider_service.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hcx-provider-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hcx-provider-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hcx-provider-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          {{- range $k, $v := .Values.hcx_provider_service }}
          - name: {{ $k }}
            value: '{{ $v }}'
          {{- end }}
          {{- range $i, $j := .Values.common }}
          - name: {{ $i }}
            value: '{{ $j }}'
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{ if eq .Values.image.tag "" }}
          image: "{{ .Values.image.repository }}"
          {{ else }}
          image: "{{ .Values.image.repository }}:{{ .Values.common.image.tag | default .Chart.AppVersion }}"
          {{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          args:
            - /bin/sh
            - -c
            - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
          resources:
            {{- toYaml .Values.hcx_provider_service.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
